### PR TITLE
Quickfix for leaderboard request and prisma init inside docker

### LINKED ISSUE #21: Docker Compose - The bot crashes after receiving a command or a new event in the game.
**Describe the bug**
The bot crashes after receiving a command or a new event in the game.

**To Reproduce**
1. Clone project from github
2. Build and run project using Docker Compose
3. Send command to bot using discord or wait for new event
5. Bot crash

**Screenshots**
13f444483d15bfe914c953ea40e8f799
02c07bc8b7b9976e6587be4d5edf3571

**Additional context**
After launching the containers using Docker Compose and entering any command into the Discord bot on the server, I receive an error in the container logs: 
```
docker-bot-2       | PrismaClientKnownRequestError:
docker-bot-2       | Invalid `this.guilds.findUnique()` invocation in
docker-bot-2       | /bot/lib/db/postgresql/repository/Guild.js:21:43
docker-bot-2       |
docker-bot-2       |   18 async findOrCreate(guildId, skipCache) {
docker-bot-2       |   19     const cache = await this.client.cache.get(`guilds:${guildId}`);
docker-bot-2       |   20     if (!cache || !!skipCache) {
docker-bot-2       |   21         let guild = await this.guilds.findUnique(
docker-bot-2       | The table `public.Guild` does not exist in the current database.
docker-bot-2       |     at An.handleRequestError (/bot/node_modules/@prisma/client/runtime/library.js:174:6929)
docker-bot-2       |     at An.handleAndLogRequestError (/bot/node_modules/@prisma/client/runtime/library.js:174:6358)
docker-bot-2       |     at An.request (/bot/node_modules/@prisma/client/runtime/library.js:174:6237)
docker-bot-2       |     at async GuildRepository.findOrCreate (/bot/lib/db/postgresql/repository/Guild.js:21:25)
docker-bot-2       |     at async InteractionHandler.run (/bot/events/InteractionHandler.js:111:21)
docker-bot-2       |     at async EventHandler.run (/bot/events/EventHandler.js:69:9) {
docker-bot-2       |   code: 'P2021',
docker-bot-2       |   clientVersion: '4.15.0',
docker-bot-2       |   meta: { table: 'public.Guild' }
docker-bot-2       | }
```

Additionally, when a new event occurs in the game, the bot throws an error: 
```
docker-postgres-1  | 2023-06-20 01:04:34.825 UTC [126] ERROR:  relation "public.Guild" does not exist at character 63
docker-postgres-1  | 2023-06-20 01:04:34.825 UTC [126] STATEMENT:  SELECT "public"."Guild"."id", "public"."Guild"."guildId" FROM "public"."Guild" WHERE ("public"."Guild"."id") IN (SELECT "t0"."id" FROM "public"."Guild" AS "t0" INNER JOIN "public"."Event" AS "j0" ON ("j0"."guildId") = ("t0"."guildId") WHERE ("j0"."type" = $1 AND "t0"."id" IS NOT NULL)) OFFSET $2
docker-bot-2       | /bot/node_modules/@prisma/client/runtime/library.js:174
```

### LINKED ISSUE #60: Docker: Unexpected end of JSON input | Failed to fetch leaderboard data.
I've created a bot in the Discord developer center, ran this project via docker but it won't start and using any command in my Discord servers gives the "The application did not respond" error

My docker run command:
```sh
docker run -d \
  --name lilith-discord-bot \
  --restart unless-stopped \
  -e TZ=Europe/Bucharest \
  -e REDIS_HOST=REDIS_IP \
  -e REDIS_PORT=REDIS_PORT \
  -e DATABASE_URL=postgresql://DB_USERNAME:DB_PASSWORD@DB_IP:DB_PORT/DB_NAME\
  -e TOKEN=MY_TOKEN \
  ghcr.io/lilith-discord-bot/lilith:main
```

My redis instance:
```sh
docker run -d \
  --name lilith-discord-bot-redis \
  --restart always \
  -p REDIS_PORT :6379 \
  -e TZ=Europe/Bucharest \
  redis:latest
```

The postgres db is correctly created and setup as I have multiple ones on my homelab

Full docker log:
```
[2023-06-27 04:15:22:1522] [ INFO ] - Launched cluster #0
[2023-06-27 04:15:22:1522] [ INFO ] - Loading 3 interactions categories.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading 1 interactions from category config.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction settings.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading 4 interactions from category d4.
[2023-06-27 04:15:22:1522] [ INFO ] - Loaded 4 event handlers
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction armory.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction chart.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction item.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction map.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading 2 interactions from category general.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction about.
[2023-06-27 04:15:22:1522] [ INFO ] - Loading interaction help.
[2023-06-27 04:15:23:1523] [ INFO ] - Shard #0 ready on cluster #0
[2023-06-27 04:15:23:1523] [ INFO ] - Event notifier has been initialized.
[2023-06-27 04:15:23:1523] [ INFO ] - Refreshing the database cache for 13 languages.
[2023-06-27 04:15:23:1523] [ INFO ] - LilithBot#7257, ready to serve 1 servers on cluster #0 (Shards: 0)
[2023-06-27 04:15:23:1523] [ INFO ] - Synchronizing interactions.
[2023-06-27 04:15:23:1523] [ ERROR ] - Unexpected end of JSON input
[2023-06-27 04:15:23:1523] [ ERROR ] - Failed to fetch leaderboard data.
[2023-06-27 04:15:44:1544] [ INFO ] - Updated 7 interaction(s).
[2023-06-27 04:15:44:1544] [ INFO ] - Interactions synchronized.
[2023-06-27 04:16:00:160] [ INFO ] - Refreshing events...
/bot/node_modules/@prisma/client/runtime/library.js:174
`)}function Em(e){return Array.isArray(e)}var no=(e,t)=>([r,...n])=>{let i="",o;if(typeof r=="string")i=r,o={values:Rt(n||[]),__prismaRawParameters__:!0},t.includes("executeRaw")&&ro(i,n,"prisma.$executeRawUnsafe(<SQL>, [...values])");else if(Em(r))switch(e._activeProvider){case"sqlite":case"mysql":{let s=new be(r,n);i=s.sql,o={values:Rt(s.values),__prismaRawParameters__:!0};break}case"cockroachdb":case"postgresql":{let s=new be(r,n);i=s.text,t.includes("executeRaw")&&ro(i,s.values,"prisma.$executeRaw`<SQL>`"),o={values:Rt(s.values),__prismaRawParameters__:!0};break}case"sqlserver":{i=to(r),o={values:Rt(n),__prismaRawParameters__:!0};break}default:throw new Error(`The ${e._activeProvider} provider does not support ${t}`)}else{switch(e._activeProvider){case"sqlite":case"mysql":i=r.sql;break;case"cockroachdb":case"postgresql":i=r.text,t.includes("executeRaw")&&ro(i,r.values,"prisma.$executeRaw(sql`<SQL>`)");break;case"sqlserver":i=to(r.strings);break;default:throw new Error(`The ${e._activeProvider} provider does not support ${t}`)}o={values:Rt(r.values),__prismaRawParameters__:!0}}return o?.values?Tu(`prisma.${t}(${i}, ${o.values})`):Tu(`prisma.${t}(${i})`),{query:i,parameters:o}};var vu={isEnabled(){return!1},getTraceParent(){return"00-10-10-00"},async createEngineSpan(){},getActiveContext(){},runInChildSpan(e,t){return t()}},io=class{isEnabled(){return this.getGlobalTracingHelper().isEnabled()}getTraceParent(t){return this.getGlobalTracingHelper().getTraceParent(t)}createEngineSpan(t){return this.getGlobalTracingHelper().createEngineSpan(t)}getActiveContext(){return this.getGlobalTracingHelper().getActiveContext()}runInChildSpan(t,r){return this.getGlobalTracingHelper().runInChildSpan(t,r)}getGlobalTracingHelper(){return globalThis.PRISMA_INSTRUMENTATION?.helper??vu}};function Pu(e){return e.includes("tracing")?new io:vu}function Mu(e,t=()=>{}){let r,n=new Promise(i=>r=i);return{then(i){return--e===0&&r(t()),i?.(n)}}}function Fu(e){return typeof e=="string"?e:e.reduce((t,r)=>{let n=typeof r=="string"?r:r.level;return n==="query"?t:t&&(r==="info"||t==="info")?"info":n},void 0)}function Su(e,t,r){let n=Cu(e,r),i=Cu(t,r),o=Object.values(i).map(a=>a[a.length-1]),s=Object.keys(i);return Object.entries(n).forEach(([a,u])=>{s.includes(a)||o.push(u[u.length-1])}),o}var Cu=(e,t)=>e.reduce((r,n)=>{let i=t(n);return r[i]||(r[i]=[]),r[i].push(n),r},{});var Mn=class{constructor(){this._middlewares=[]}use(t){this._middlewares.push(t)}get(t){return this._middlewares[t]}has(t){return!!this._middlewares[t]}length(){return this._middlewares.length}};var Ru=S(Qt());function Fn(e){return typeof e.batchRequestIdx=="number"}function Au({result:e,modelName:t,select:r,extensions:n}){let i=n.getAllComputedFields(t);if(!i)return e;let o=[],s=[];for(let a of Object.values(i)){if(r){if(!r[a.name])continue;let u=a.needs.filter(l=>!r[l]);u.length>0&&s.push(Bi(u))}Tm(e,a.needs)&&o.push(vm(a,Ze(e,o)))}return o.length>0||s.length>0?Ze(e,[...o,...s]):e}function Tm(e,t){return t.every(r=>ci(e,r))}function vm(e,t){return st(Ye(e.name,()=>e.compute(t)))}function Cn({visitor:e,result:t,args:r,runtimeDataModel:n,modelName:i}){if(Array.isArray(t)){for(let s=0;s<t.length;s++)t[s]=Cn({result:t[s],args:r,modelName:i,runtimeDataModel:n,visitor:e});return t}let o=e(t,i,r)??t;return r.include&&Ou({includeOrSelect:r.include,result:o,parentModelName:i,runtimeDataModel:n,visitor:e}),r.select&&Ou({includeOrSelect:r.select,result:o,parentModelName:i,runtimeDataModel:n,visitor:e}),o}function Ou({includeOrSelect:e,result:t,parentModelName:r,runtimeDataModel:n,visitor:i}){for(let[o,s]of Object.entries(e)){if(!s||t[o]==null)continue;let u=n.models[r].fields.find(c=>c.name===o);if(!u||u.kind!=="object"||!u.relationName)continue;let l=typeof s=="object"?s:{};t[o]=Cn({visitor:i,result:t[o],args:l,modelName:u.type,runtimeDataModel:n})}}var Sn=class{constructor(t){this.options=t;this.tickActive=!1;this.batches={}}request(t){let r=this.options.batchBy(t);return r?(this.batches[r]||(this.batches[r]=[],this.tickActive||(this.tickActive=!0,process.nextTick(()=>{this.dispatchBatches(),this.tickActive=!1}))),new Promise((n,i)=>{this.batches[r].push({request:t,resolve:n,reject:i})})):this.options.singleLoader(t)}dispatchBatches(){for(let t in this.batches){let r=this.batches[t];delete this.batches[t],r.length===1?this.options.singleLoader(r[0].request).then(n=>{n instanceof Error?r[0].reject(n):r[0].resolve(n)}).catch(n=>{r[0].reject(n)}):this.options.batchLoader(r.map(n=>n.request)).then(n=>{if(n instanceof Error)for(let i=0;i<r.length;i++)r[i].reject(n);else for(let i=0;i<r.length;i++){let o=n[i];o instanceof Error?r[i].reject(o):r[i].resolve(o)}}).catch(n=>{for(let i=0;i<r.length;i++)r[i].reject(n)})}}get[Symbol.toStringTag](){return"DataLoader"}};var Pm=B("prisma:client:request_handler"),An=class{constructor(t,r){this.logEmitter=r,this.client=t,this.dataloader=new Sn({batchLoader:n=>{let{transaction:i,protocolEncoder:o,otelParentCtx:s}=n[0],a=o.createBatch(n.map(c=>c.protocolMessage)),u=this.client._tracingHelper.getTraceParent(s),l=n.some(c=>c.protocolMessage.isWrite());return this.client._engine.requestBatch(a,{traceparent:u,transaction:Mm(i),containsWrite:l,customDataProxyFetch:n[0].customDataProxyFetch})},singleLoader:n=>{let i=n.transaction?.kind==="itx"?$u(n.transaction):void 0;return this.client._engine.request(n.protocolMessage.toEngineQuery(),{traceparent:this.client._tracingHelper.getTraceParent(),interactiveTransaction:i,isWrite:n.protocolMessage.isWrite(),customDataProxyFetch:n.customDataProxyFetch})},batchBy:n=>n.transaction?.id?`transaction-${n.transaction.id}`:n.protocolMessage.getBatchId()})}async request({protocolMessage:t,protocolEncoder:r,dataPath:n=[],callsite:i,modelName:o,rejectOnNotFound:s,clientMethod:a,args:u,transaction:l,unpacker:c,extensions:p,otelParentCtx:f,otelChildCtx:m,customDataProxyFetch:d}){try{let g=await this.dataloader.request({protocolMessage:t,protocolEncoder:r,transaction:l,otelParentCtx:f,otelChildCtx:m,customDataProxyFetch:d}),b=g?.data,h=g?.elapsed,x=this.unpack(t,b,n,c);return Ga(x,a,o,s),o&&(x=this.applyResultExtensions({result:x,modelName:o,args:u,extensions:p})),process.env.PRISMA_CLIENT_GET_TIME?{data:x,elapsed:h}:x}catch(g){this.handleAndLogRequestError({error:g,clientMethod:a,callsite:i,transaction:l,args:u})}}handleAndLogRequestError(t){try{this.handleRequestError(t)}catch(r){throw this.logEmitter&&this.logEmitter.emit("error",{message:r.message,target:t.clientMethod,timestamp:new Date}),r}}handleRequestError({error:t,clientMethod:r,callsite:n,transaction:i,args:o}){if(Pm(t),Fm(t,i)||t instanceof ve)throw t;if(t instanceof re&&Cm(t)){let a=Du(t.meta);vn({args:o,errors:[a],callsite:n,errorFormat:this.client._errorFormat,originalMethod:r})}let s=t.message;throw n&&(s=De({callsite:n,originalMethod:r,isPanic:t.isPanic,showColors:this.client._errorFormat==="pretty",message:s})),s=this.sanitizeMessage(s),t.code?new re(s,{code:t.code,clientVersion:this.client._clientVersion,meta:t.meta,batchRequestIdx:t.batchRequestIdx}):t.isPanic?new ge(s,this.client._clientVersion):t instanceof ne?new ne(s,{clientVersion:this.client._clientVersion,batchRequestIdx:t.batchRequestIdx}):t instanceof Q?new Q(s,this.client._clientVersion):t instanceof ge?new ge(s,this.client._clientVersion):(t.clientVersion=this.client._clientVersion,t)}sanitizeMessage(t){return this.client._errorFormat&&this.client._errorFormat!=="pretty"?(0,Ru.default)(t):t}unpack(t,r,n,i){if(!r)return r;r.data&&(r=r.data);let o=t.deserializeResponse(r,n);return i?i(o):o}applyResultExtensions({result:t,modelName:r,args:n,extensions:i}){return i.isEmpty()||t==null||!this.client._runtimeDataModel.models[r]?t:Cn({result:t,args:n??{},modelName:r,runtimeDataModel:this.client._runtimeDataModel,visitor(s,a,u){let l=Te(a);return Au({result:s,modelName:l,select:u.select,extensions:i})}})}get[Symbol.toStringTag](){return"RequestHandler"}};function Mm(e){if(!!e){if(e.kind==="batch")return{kind:"batch",options:{isolationLevel:e.isolationLevel}};if(e.kind==="itx")return{kind:"itx",options:$u(e)};Le(e,"Unknown transaction kind")}}function $u(e){return{id:e.id,payload:e.payload}}function Fm(e,t){return Fn(e)&&t?.kind==="batch"&&e.batchRequestIdx!==t.index}function Cm(e){return e.code==="P2009"||e.code==="P2012"}function Du(e){if(e.kind==="Union")return{kind:"Union",errors:e.errors.map(Du)};if(Array.isArray(e.selectionPath)){let[,...t]=e.selectionPath;return{...e,selectionPath:t}}return e}function Iu(e){return e.map(t=>{let r={};for(let n of Object.keys(t))r[n]=Nu(t[n]);return r})}function Nu({prisma__type:e,prisma__value:t}){switch(e){case"bigint":return BigInt(t);case"bytes":return Buffer.from(t,"base64");case"decimal":return new he(t);case"datetime":case"date":return new Date(t);case"time":return new Date(`1970-01-01T${t}Z`);case"array":return t.map(Nu);default:return t}}var ju=S(Br());var ku=["datasources","errorFormat","log","__internal","rejectOnNotFound"],Lu=["pretty","colorless","minimal"],_u=["info","query","warn","error"],Sm={datasources:(e,t)=>{if(!!e){if(typeof e!="object"||Array.isArray(e))throw new H(`Invalid value ${JSON.stringify(e)} for "datasources" provided to PrismaClient constructor`);for(let[r,n]of Object.entries(e)){if(!t.includes(r)){let i=$t(r,t)||`Available datasources: ${t.join(", ")}`;throw new H(`Unknown datasource ${r} provided to PrismaClient constructor.${i}`)}if(typeof n!="object"||Array.isArray(n))throw new H(`Invalid value ${JSON.stringify(e)} for datasource "${r}" provided to PrismaClient constructor.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

PrismaClientKnownRequestError: 
Invalid `this.client.database.notification.findFirst()` invocation in
/bot/lib/notifications/EventNotifier.js:39:67

  36     return;
  37 }
  38 for (let [key, event] of Object.entries(events)) {
→ 39     const exist = await this.client.database.notification.findFirst(
The table `public.Notification` does not exist in the current database.
    at An.handleRequestError (/bot/node_modules/@prisma/client/runtime/library.js:174:6929)
    at An.handleAndLogRequestError (/bot/node_modules/@prisma/client/runtime/library.js:174:6358)
    at An.request (/bot/node_modules/@prisma/client/runtime/library.js:174:6237)
    at async EventNotifier.refresh (/bot/lib/notifications/EventNotifier.js:39:27) {
  code: 'P2021',
  clientVersion: '4.15.0',
  meta: { table: 'public.Notification' }
}

Node.js v18.16.1
[2023-06-27 04:16:00:160] [ INFO ] - Loading 3 interactions categories.
[2023-06-27 04:16:00:160] [ INFO ] - Loading 1 interactions from category config.
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction settings.
[2023-06-27 04:16:00:160] [ INFO ] - Loading 4 interactions from category d4.
[2023-06-27 04:16:00:160] [ INFO ] - Loaded 4 event handlers
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction armory.
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction chart.
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction item.
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction map.
[2023-06-27 04:16:00:160] [ INFO ] - Loading 2 interactions from category general.
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction about.
[2023-06-27 04:16:00:160] [ INFO ] - Loading interaction help.
[2023-06-27 04:16:01:161] [ INFO ] - Shard #0 ready on cluster #0
[2023-06-27 04:16:01:161] [ INFO ] - Event notifier has been initialized.
[2023-06-27 04:16:01:161] [ INFO ] - Cluster #0 is ready
[2023-06-27 04:16:01:161] [ INFO ] - Refreshing the database cache for 13 languages.
[2023-06-27 04:16:01:161] [ INFO ] - LilithBot#7257, ready to serve 1 servers on cluster #0 (Shards: 0)
[2023-06-27 04:16:01:161] [ INFO ] - Synchronizing interactions.
[2023-06-27 04:16:02:162] [ ERROR ] - Unexpected end of JSON input
[2023-06-27 04:16:02:162] [ ERROR ] - Failed to fetch leaderboard data.
[2023-06-27 04:16:22:1622] [ INFO ] - Updated 7 interaction(s).
[2023-06-27 04:16:22:1622] [ INFO ] - Interactions synchronized.
(loop)
```

### PR DESCRIPTION
**Pull request by Piekario**
fixes #60, fixes #21

### CODE REVIEW

**Comment by glazk0** [comment]
Hey there, gonna review that! Sorry for the late answer, I've been very busy lately.

**Comment by glazk0** [comment]
After review, looks fine so far, for the Docker, I'm running through this:

image

**Comment by Piekario** [comment]
I added execute permissions with chmod. What version of Docker and Docker Compose are You using?

**Comment by glazk0** [comment]
> I added execute permissions with chmod. What version of Docker and Docker Compose are You using?

Thanks!

Docker: 20.10.20
Docker-compose: 2.12.1

Running on macOS Ventura

**Comment by glazk0** [comment]
I guess we don't care about this once it's done ? 

image

**Comment by glazk0** [comment]
Update: I'm totally dumb cause I actually forgot to work with migrations so we are all using Prisma the wrong way xD

I'm gonna push actual migrations soon and will change the migrate thing to deploy that will check if there is new migration that need to be done on your DB.

**Comment by glazk0** [comment]
Waiting for you both to test and approve this change that will make our life easier later.

Also you may need to either reset your volumes (since they will be stocked in postgres for checking purpose) or it will reset your data.

image

**Pull request merged**
